### PR TITLE
[test] fix conditions matchingpennies

### PR DESCRIPTION
**Pull request by sappelhoff**
follow up to #508 

the tests only caught this after the pr was merged ... maybe some caching thing.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by hoechenberger** [comment]
> the tests only caught this after the pr was merged ... maybe some caching thing.

No, by default we only run tests on `ds000247` for PRs
To run tests for a different dataset, the commit message must contain the string `[circle dataset_name]`, e.g., `[circle eeg_matchingpennies]` to run the test with the matchingpennies dataset. Alternatively, `[circle full]` runs tests on all datasets.

On `main`, we run **all** tests, hence the problem was only caught after merging.

**Comment by hoechenberger** [comment]
Haha now we both pushed again 😅🙈 sorry about that!!

**Comment by sappelhoff** [comment]
haha, no worries- thanks for the explanation :)

**Comment by hoechenberger** [comment]
Thank you, @sappelhoff!

**Pull request merged**
