### PR TITLE
pyvista was renamed to pyvistaqt

### PR DESCRIPTION
**Pull request by agramfort**
### Before merging …

- [ ] Changelog has been updated (`docs/source/changes.md`)

### CODE REVIEW

**Comment by agramfort** [comment]
this should fix errors like https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/2378/workflows/bd1a74ca-08a7-4e3e-a841-3c5bb3c6de0f/jobs/15743/parallel-runs/0/steps/0-104

**Comment by hoechenberger** [comment]
Thanks!!

**Comment by agramfort** [comment]
but it's not fixed yet... I need to try more

>

**Comment by hoechenberger** [comment]
Oh. 😅

**Pull request merged**
