### PR TITLE
Forward solution routine

### PR DESCRIPTION
**Pull request by ktavabi**
Looks like the forward solution failsafe routine needs a better check for existing coregistration `trans.fif` file(s)

### Before merging …

- [ ] Changelog has been updated (`docs/source/changes.md`)

### CODE REVIEW

**Comment by hoechenberger** [comment]
Great, thank you!

**Comment by ktavabi** [comment]
FYI there were several additional points along the way where `overwrite=True` was useful.

**Comment by hoechenberger** [comment]
> FYI there were several additional points along the way where `overwrite=True` was useful;

The idea would be that we'd always overwrite data in `derivatives` on a re-run of the pipeline. If you know of any other places where `overwrite=True` would be needed, please feel free to open another PR! There were some upstream changes in MNE-Python where an `overwrite` parameter was added to a bunch of save functions, and it usually defaults to `False`.

**Comment by agramfort** [comment]
thx @ktavabi 🙏

**Pull request merged**
