### PR TITLE
MAINT: Remove URL-based reqs

### PR DESCRIPTION
**Pull request by larsoner**
I tried to upload to PyPI and got:
```
Invalid value for requires_dist. Error: Can't have direct dependency: "autoreject @ https://api.github.com/repos/autoreject/autoreject/zipball/master ; extra == 'dev'"
```
It seems that PyPI does not want any requirements to be URL-based, so this PR removes the `dev` target that contained all URL-based `main` requirements.

### CODE REVIEW

**Comment by larsoner** [comment]
... whereas on this PR:

https://pypi.org/project/mne-bids-pipeline/

**Comment by hoechenberger** [comment]
Do we need to cut a new release of autoreject?

**Comment by hoechenberger** [comment]
Oh never mind, I misunderstood what was going on here. Mmh that's a bummer really!

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
> I tried to upload to PyPI and got:

Allegedly, `twine check` should catch this; we should add this to our workflow

**Comment by larsoner** [comment]
> Allegedly, twine check should catch this; we should add this to our workflow

Maybe it won't actually? I didn't read the whole thing but this is still open: https://github.com/pypa/twine/issues/430

But in any case, I now added:

1. A wheel build action, including a `twine check --strict`
2. A PyPI-upload action with proper PyPI var
3. `setuptools_scm` var `tag_regex` to strip the `v` from tags so that `v1.0.0` can be the name of our tag in our first real release (following MNE-Python convention)

**Comment by larsoner** [comment]
> Do we need to cut a new release of autoreject?

This would be a good idea actually, since the latest release there was some fix of `nan` handling I think?

**Comment by hoechenberger** [comment]
Thanks @larsoner!

**Pull request merged**
