### PR TITLE
[MRG] Automatically run Circle every day at 4 AM

### PR DESCRIPTION
**Pull request by hoechenberger**
To get informed about breaking changes upstream early!

### CODE REVIEW

**Comment by hoechenberger** [comment]
Scheduled runs are actually working, here is the one from this morning:
https://app.circleci.com/pipelines/github/mne-tools/mne-study-template/603/workflows/7f198f6b-9dea-49db-a2bc-98d2f1ee1228

I believe once it fails, we'll receive an email.

**Comment by sappelhoff** [comment]
this seems like a nice feature, thanks @hoechenberger perhaps also something for MNE-BIDS.

**Comment by hoechenberger** [comment]
@sappelhoff 
https://github.com/mne-tools/mne-bids/pull/512

**Comment by hoechenberger** [comment]
Tonight it should break because MNE-BIDS dropped `make_bids_basename`; let's see what happens and if / how we get notified.

**Comment by hoechenberger** [comment]
I received an email 🥳

image

**Comment by jasmainak** [comment]
you know life is amazing when emails from bots make you happy ;-)

**Pull request merged**
