### PR TITLE
Add configuration and system info to the reports

### PR DESCRIPTION
**Pull request by hoechenberger**
### Before merging …

- [x] Changelog has been updated (`docs/source/changes.md`)

### CODE REVIEW

**Comment by hoechenberger** [comment]
@agramfort WDYT? Should unnahbar move the new stuff to the very beginning of the report, so the first thing you see is the config?

Or maybe... move the config to the beginning but keep the system info at the bottom?

https://output.circle-artifacts.com/output/job/65f48332-72ec-4d25-8d36-6ef4b69791e1/artifacts/0/site/examples/ds000247/sub-0002_ses-01_task-rest_report.html

**Comment by agramfort** [comment]
At the bottom it’s 👌 for me

**Comment by hoechenberger** [comment]
You mean like it is now?

**Comment by agramfort** [comment]
Yes

**Pull request merged**
