### PR TITLE
ENH: Streamline ICA reporting

### LINKED ISSUE #880: Align report sections with pipeline steps
I think the epochs should be after the ICA cleaning, to reflect the order of processing steps, no?

Capture d’écran du 2024-03-08 15-34-50

### PR DESCRIPTION
**Pull request by larsoner**
### Before merging …

- [x] Changelog has been updated (`docs/source/changes.md`)

1. Moved all ICA reports to the main report:

   image

2. Added docs suggesting manual intervention is required (maybe it should be suggested instead?) when using ICA to take care of the doc part of #881
3. Add just one subject's data for `ERP_CORE` (plus the average) to the website to cut size down.
4. Add script to remove examples from old versions so we don't have to remove their docs anymore (they go down to like 6MB or something!).

Closes #880

### CODE REVIEW

**Comment by larsoner** [comment]
@SophieHerbst can you look to see if the unified report titles and contents seem reasonable to you? Here is an example

https://output.circle-artifacts.com/output/job/3ed5bcd9-e31f-48c1-96c5-b582bd7bccfc/artifacts/0/site/examples/ERP_CORE/sub-015_ses-N170_task-N170_report.html#ICA__epochs_for_fitting

**Comment by SophieHerbst** [comment]
@larsoner the report looks good to me! 
Do I understand correctly that there is only one single report now?

**Comment by larsoner** [comment]
Yep!

**Comment by hoechenberger** [comment]
Is this good to go? are you waiting for my review?

**Comment by larsoner** [comment]
@hoechenberger just a friendly reminder about this one when you get a chance!

**Comment by hoechenberger** [comment]
I won't have time to review it before the end of this week. If this is rather urgent, go ahead and merge and we'll do a follow-up PR if need be

**Comment by larsoner** [comment]
I'll fix the conflict here and merge, happy to do a follow-up PR if needed though @hoechenberger !

**Comment by hoechenberger** [comment]
ok with me, sorry for the delay here

**Comment by larsoner** [comment]
Added a workaround for https://github.com/joblib/joblib/issues/1572

**Pull request merged**
