### PR TITLE
BUG: Fix bug with empty room processing

### LINKED ISSUE #759: BUG: Reference run not guaranteed to be processed before noise runs
This has been discussed on the MNE Forum [here](https://mne.discourse.group/t/mne-bids-pipeline-maxwell-filter-reference-run-rank-mismatch/7144). 

I received an error when running the Maxwell filter step in the MNE-BIDS-Pipeline, saying that the rank of the data in the reference rune does not match the empty room data rank, see below:
```
[10:55:33] │ ❌ preprocessing/_02_maxfilter sub-09 run-01 A critical error occurred. The error message was: Reference run data rank 73.0 does not match empty-room data rank 71.0 after Maxwell filtering. This indicates that the data were processed  differently.

Aborting pipeline run. The full traceback is:

Traceback (most recent call last):

  File "/home/ma09/.conda/envs/my_mne1.4_fix/lib/python3.11/site-packages/mne_bids_pipeline/_run.py", line 54, in wrapper
    out = memory.cache(func)(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ma09/.conda/envs/my_mne1.4_fix/lib/python3.11/site-packages/mne_bids_pipeline/_run.py", line 263, in wrapper
    out_files = memorized_func(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ma09/.conda/envs/my_mne1.4_fix/lib/python3.11/site-packages/joblib/memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ma09/.conda/envs/my_mne1.4_fix/lib/python3.11/site-packages/joblib/memory.py", line 537, in _cached_call
    out, metadata = self.call(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ma09/.conda/envs/my_mne1.4_fix/lib/python3.11/site-packages/joblib/memory.py", line 779, in call
    output = self.func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ma09/.conda/envs/my_mne1.4_fix/lib/python3.11/site-packages/mne_bids_pipeline/steps/preprocessing/_02_maxfilter.py", line 264, in run_maxwell_filter
    raise RuntimeError(msg)

RuntimeError: Reference run data rank 73.0 does not match empty-room data rank 71.0 after Maxwell filtering. This indicates that the data were processed  differently.
```
This occurred only with a specific subject in the dataset and it has to do with which run I set as reference. If I set mf_reference_run = '03', I get the error, however, if I set mf_reference_run = '01', then the Maxwell filter step runs fine without an error.

### PR DESCRIPTION
**Pull request by larsoner**
### Before merging …

- [x] Changelog has been updated (`docs/source/changes.md`)

@allermat can you try this branch? In theory you should not need to delete any derivatives, just update to this branch and run.

Closes #759

Only mentioning the `epochs` bug fix here since the one @allermat is actually hitting is a within-release (within the last week I think!) bugfix

### CODE REVIEW

**Comment by larsoner** [comment]
Okay turns out the epochs were okay because we already use the min across runs, so I adjusted the change log and title. I still think #760 is probably the best way to deal with this issue for now, especially when (later) combined with empirical rank estimation which will be necessary for movement compensation.

**Comment by larsoner** [comment]
@hoechenberger feel free to merge if you're happy, I think it should fix the bug but even if it doesn't is a nice/helpful refactor (again)

**Comment by larsoner** [comment]
... I also realized that the head pos text file was being written as `ds004229/sub-102/meg/sub-102_task-amnoise` for example, this fixes it so it's written as `ds004229/sub-102/meg/sub-102_task-amnoise_headpos.txt`

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thanks @larsoner

**Pull request merged**
