### PR TITLE
using caching for get_runs_all_subjects to speed up get_runs

### LINKED ISSUE #715: slow down with loads of subjects due to quadratic cast of get_runs function
@apmellot played with a dataset with 1400 subjects and the pipeline appeared super slow to get started. The quality step takes more than a day on the NFS disks... When profiling it seems the bottleneck is in the get_runs function. It calls get_runs_all_subjects for all subject so it seems we have a quadratic complexity here.

It seems we need to change the logic or use more caching.

### PR DESCRIPTION
**Pull request by agramfort**
closes #715

@apmellot can you see if it fixes your problem?

### CODE REVIEW

**Comment by apmellot** [comment]
@agramfort Yes it fixes my problem!

**Comment by hoechenberger** [comment]
I didn't really take the time to look, but I expected the `pkg_resources` issue to be solved already upstream via https://github.com/mne-tools/mne-python/pull/11454 -- maybe some bits were forgotten there?

**Review by larsoner — APPROVED** [review]

**Review by hoechenberger — APPROVED** [review]

**Comment by larsoner** [comment]
@hoechenberger downloading `eeg_matchingpennies` is currently at ~40 minutes and will probably time out soon. It's a ~350 MB dataset for subject 05 (the one we use) -- I'm going to just make an `osf.io` mirror of the dataset I think...

**Comment by agramfort** [comment]
I just restarted the CI

**Comment by agramfort** [comment]
sounds good!

**Comment by hoechenberger** [comment]
> I'm going to just make an `osf.io` mirror of the dataset I think...

Go for it :)

**Pull request merged**
