### PR TITLE
MAINT: Move to pip

### PR DESCRIPTION
**Pull request by larsoner**
Let's see if this is faster

### CODE REVIEW

**Comment by hoechenberger** [comment]
Nice! Seems you cut down the setup duration from ~8.5 to ~2.5 minutes

**Comment by hoechenberger** [comment]
@larsoner Is this good to merge?

**Comment by larsoner** [comment]
I don't love that the keyserver I used to install a recent enough `datalad` timed out a few times during testing. But we can give it a shot and figure out a workaround if it fails, so +1 for merge from me

**Comment by hoechenberger** [comment]
Thanks @larsoner!

**Pull request merged**
