### PR TITLE
Rework high-pass filtering for ICA

### LINKED ISSUE #285: Config error when specifying no high-pass filtering on the raw data
The checks to make sure ica_l_freq < l_freq does not take into account the possibility where l_freq is None.

The code fails on these checks: 
- https://github.com/mne-tools/mne-bids-pipeline/blob/0c67af9e7587bf6639def22c553e0eb64927b371/config.py#L1306
- https://github.com/mne-tools/mne-bids-pipeline/blob/0c67af9e7587bf6639def22c553e0eb64927b371/scripts/preprocessing/04a-run_ica.py#L72
- https://github.com/mne-tools/mne-bids-pipeline/blob/0c67af9e7587bf6639def22c553e0eb64927b371/scripts/preprocessing/04a-run_ica.py#L75

both when l_freq is None and ica_l_freq > 0 (expected to raise an error but currently the error is a TypeError), and when l_freq and ica_l_freq are both None.

This can be reproduced by setting l_freq and ica_l_freq to None in the config file.

I don't know what the best practice is: I want to estimate the low-frequency power spectrum, so I can't have my data high-passed. However I'm not sure it is a good idea to run the ICA with no high-pass filter.
I was able to get the code running with a few modifications, but I don't know if I should include highpass filtering for the ICA or not.

### PR DESCRIPTION
**Pull request by hoechenberger**
Fixes #285

- More validation
- drop support for "dangerous" stuff (no filtering, cutoff < 1 Hz)

We need to decide sometime where and when to do the validation: in the config file or in the scripts?

cc @MerlinDumeur @agramfort

### CODE REVIEW

**Review by agramfort — COMMENTED** [review]
I would get to have the opinion of more people for the 1Hz or to provide a reference so we know where this number comes from. So it's not just the two of us @hoechenberger :)

**Comment by jasmainak** [comment]
I'm in support of 1 Hz filter. Perhaps documenting the rationale might be enough. I think for EEG these slow drifts are really a problem. Perhaps less so for MEG if you have done SSS. 

FWIW, we had a [demo](http://mne.tools/mne-biomag-group-demo/auto_examples/demos/plot_fanning.html#sphx-glr-auto-examples-demos-plot-fanning-py) in the past that showed what happens if you don't highpass at 1 Hz vs if you use SSS vs baseline (also kind of a highpass but less aggressive). In the biomag demo paper, I think we tried to argue that extending the time window will make the data return to baseline. So, what's in between must be brain signals. However, if we look carefully again -- it seems the pre-stimulus baseline has lower std dev than the baseline later with no (or 0.1 Hz) highpass. Thus, I think you really need 1 Hz highpass, particularly for EEG data.

**Comment by hoechenberger** [comment]
@agramfort feel free to merge if happy

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @hoechenberger @MerlinDumeur !

**Pull request merged**
