### PR TITLE
Test with MNE-Python's "Deprecations 1.1" branch before merging it

### PR DESCRIPTION
**Pull request by hoechenberger**
Do not merge. This is just to test if https://github.com/mne-tools/mne-python/pull/11008 will break the pipeline.

cc @drammock

### CODE REVIEW

**Comment by hoechenberger** [comment]
@agramfort Some tests fail, could you take a look please?

**Comment by agramfort** [comment]
See https://github.com/autoreject/autoreject/pull/284 it's a pb in autoreject

**Comment by agramfort** [comment]
@hoechenberger can you push an empty commit or restart the CI to see if it works now?

**Comment by larsoner** [comment]
https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/3079/workflows/10076ae4-124f-4889-a4a5-49d7429d1a3d

We might have to look manually to see if it's green

**Pull request closed without merging**
