### PR TITLE
MAINT: Cleaner hook into mkdocstrings-python

### PR DESCRIPTION
**Pull request by larsoner**
No need for changelog update I think since this is really just internal cleanup. Trying the suggestion in https://github.com/mkdocstrings/mkdocstrings/issues/615#issuecomment-2081550319

### CODE REVIEW

**Comment by larsoner** [comment]
@hoechenberger another persistent OpenNeuro problem :disappointed:

**Comment by hoechenberger** [comment]
@larsoner Seems like a bug in the OpenNeuro server…

**Comment by hoechenberger** [comment]
@larsoner I'm looking into this now.

**Comment by hoechenberger** [comment]
@larsoner I cannot reproduce this locally…

**Comment by hoechenberger** [comment]
Oh so it suddenly started working again? :)

**Comment by larsoner** [comment]
Yes just have been a bad day, restarting it days later fixed it

**Pull request merged**
