### PR TITLE
MAINT: Autogenerate step table

### LINKED ISSUE #617: DOC: steps.md is out of date
https://mne.tools/mne-bids-pipeline/features/steps.html

We should add to `tests/test_documented.py` that each script name appears in that doc, see it fail (TDD), and then fix it. Probably after https://github.com/mne-tools/mne-bids-pipeline/issues/616 so it's not immediately wrong.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #617.

The table is now generated based on the `SCRIPT_MODULES` + docstrings of the `__init__.py` and `_XX_XXX.py` scripts.

No need for `latest.inc` update I think because it's just a doc fix.

### CODE REVIEW

**Comment by agramfort** [comment]
@larsoner can you share the rendered doc when you have it? 🙏

**Review by hoechenberger — APPROVED** [review]
nice!

**Comment by larsoner** [comment]
https://output.circle-artifacts.com/output/job/f1d8f3f9-5e1d-4d31-8a56-658b4534e8c9/artifacts/0/site/features/steps.html

**Comment by agramfort** [comment]
thanks @larsoner 🙏

**Pull request merged**
