### PR TITLE
Add generalization across time

### PR DESCRIPTION
**Pull request by hoechenberger**
### Before merging …

- [x] Changelog has been updated (`docs/source/changes.md`)

### CODE REVIEW

**Comment by hoechenberger** [comment]
@agramfort 

See

https://output.circle-artifacts.com/output/job/62744211-7b20-45d7-86b5-996c9440bc96/artifacts/0/site/examples/ERP_CORE/sub-average_ses-N400_task-N400_report.html#global11

(Use the slider)

image

**Comment by agramfort** [comment]
I am not too convinced about sliders. Each section can be folded or hidden
using tags. It makes things more harder to discover I think

**Comment by hoechenberger** [comment]
I agree, I will come up with a solution.

**Comment by hoechenberger** [comment]
This is now blocked by https://github.com/mne-tools/mne-python/pull/10694

**Review by agramfort — APPROVED** [review]
beautiful !

**Comment by agramfort** [comment]
thx @hoechenberger !

**Pull request merged**
