### PR TITLE
MAINT: Simplify by removing fire

### PR DESCRIPTION
**Pull request by larsoner**
This PR proposes to remove `fire` in support of `optparse`. `Fire` has the advantage of automatically turning a function into a command-line util (neat magic!), but I think it comes with several problematic deficiencies:

1. `-h` and `--help` are not autodetected, we needed to work around it.
2. Extra/wrong arguments/switches are not detected properly, we needed to work around it.
3. We have to do a bunch of `str` mangling to deal with the fact that Fire converts stuff like `--subject=123` into an `int`, `optparse` makes this stuff explicit
4. It does not support `store_true`-style switches like just doing `--interactive` to enable interactive mode -- you have to pass `--interactive=1` which is bad/non-standard Unix command-line interfacing
5. `Fire` is nowhere near as standard as `optparse`, so it takes some time/effort to understand what it's doing, and fix it when it's doing something wrong.

This PR fixes all of these issues by just using `optparse`. The result is one fewer dependency, and more deletions (-93) than insertions (+70) to get there. It also adds some advantages that we get immediately from `optparse`, like making it easy to provide the config as an argument instead of as `--config`, so now you can do `mne_bids_pipeline whatever_config.py` directly (just like we do with `mne_browse_raw --fif file.fif` and `mne_browse_raw file.fif`), which I've implemented here already.

### CODE REVIEW

**Comment by larsoner** [comment]
... and added a commit to trivially add `mne_bids_pipeline --version` support, which is nice, too

**Comment by hoechenberger** [comment]
@larsoner It seems the tests didn't run?

**Comment by larsoner** [comment]
I `ci skip`ped the `--version` commit because it seemed unnecessary (worked fine locally), the commit before that was green but CircleCI had a bug where it didn't report the status

https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/3411/workflows/90e6d74e-06e4-469a-ba4e-d09fb3a984ba

**Comment by hoechenberger** [comment]
@larsoner Thanks! I merged `main` and enabled automerge.

**Pull request merged**
