### PR TITLE
Only assemble epochs for the conditions of interest if specified

### PR DESCRIPTION
**Pull request by agramfort**
cc @dengemann 

let's see if it makes CIs happy

### CODE REVIEW

**Comment by hoechenberger** [comment]
No way this can be so simple 😲 Really excited to see what CI says!!

**Comment by hoechenberger** [comment]
@agramfort Tests seem to pass!!

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thanks @agramfort

**Comment by hoechenberger** [comment]
We might be able to simplify some code in other scripts now (for example, when creating evokeds), but it would require some careful testing

**Comment by dengemann** [comment]
Awesome @agramfort thank you!!! Love it that you went with my somewhat brutal proposal :)

**Pull request merged**
