### PR TITLE
Various doc improvements

### PR DESCRIPTION
**Pull request by hoechenberger**
### Before merging …

- [ ] Changelog has been updated (`docs/source/changes.md`)

### CODE REVIEW

**Comment by larsoner** [comment]
Looks good from a source perspective, feel free to merge when green and the rendering looks good @hoechenberger ! FYI for PRs like this you can commit with `[circle ds003775]` or similar to save a lot of CI cycles and get faster turnaround

**Comment by larsoner** [comment]
Tests now pass (fixed indentation and line `key`). Current rendering: https://output.circle-artifacts.com/output/job/ca821a62-a99f-473c-be4b-422fe2a731a9/artifacts/0/site/index.html

**Comment by hoechenberger** [comment]
Thanks Eric!

**Comment by larsoner** [comment]
@hoechenberger still WIP or good to merge?

**Comment by hoechenberger** [comment]
@larsoner Still WIP!!

**Comment by hoechenberger** [comment]
@larsoner I'm still not 100% happy but I think this can be merged and we can iterate at some later time

**Comment by hoechenberger** [comment]
Rendered docs:
https://output.circle-artifacts.com/output/job/7cb7704c-6141-4de5-af57-9c10c3dd8a1d/artifacts/0/site/index.html

**Comment by larsoner** [comment]
Time for hopefully last release before inclusion with MNE 1.3 installers?

**Comment by hoechenberger** [comment]
Yep sounds good to me!

**Pull request merged**
