### PR TITLE
no proj ON in unclean epochs

### PR DESCRIPTION
**Pull request by agramfort**
cc @hoechenberger

### CODE REVIEW

**Comment by hoechenberger** [comment]
Do we need to explicitly apply the proj at some later time point during processing?

**Comment by agramfort** [comment]
it's gets applied by read_epochs by default... don't ask me why...

>

**Comment by hoechenberger** [comment]
We have `proj=True` when creating `Epochs` in script 4 too, I believe this need to be changed as well..?

> it's gets applied by read_epochs by default

Does this mean that when reading the epochs in step 5 (where we apply ICA) we should pass `proj=False` to `read_epochs()`?

**Comment by agramfort** [comment]
I think it's ok to apply proj before doing SSP or ICA.

I want to have epochs without proj to be able to spot bad channels more
easily

>

**Comment by hoechenberger** [comment]
Ok, sounds fair to me. I've restarted the one failing CI

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thanks @agramfort!

**Pull request merged**
