### PR TITLE
MAINT: Fix bug with overrides

### PR DESCRIPTION
**Pull request by larsoner**
Help with #684.

Short of updating all structure since @hoechenberger is working on that, this just:

1. Makes sure we use consistent taglines across PyPI and our homepage
2. Adds a "last updated" to the footer
3. Fixes the `overrides` so that the banner hopefully works

Committed with `[circle ds003392]` to speed up the doc build

### CODE REVIEW

**Comment by larsoner** [comment]
@hoechenberger feel free to merge if you're happy: https://output.circle-artifacts.com/output/job/3c2180ee-d055-41ef-8eaa-c4970830e226/artifacts/0/site/index.html

Should we cut a 1.0.3 once this is merged, or wait for your doc updates?

**Comment by larsoner** [comment]
Going to merge this one and we can iterate further separately. Happy to help with any rebase/merge conflicts this creates!

**Comment by larsoner** [comment]
This appears to have fixed the banner!

Screenshot 2022-12-12 at 12 08 38 PM

**Comment by hoechenberger** [comment]
Nice!

**Pull request merged**
